Repository softeer5th/Team2-Getit, pull requests merged in 2025-01, with the labels that each got.

#2 [UNI-36] feat : Vite 프로젝트 초기 설정 & 디자인 시스템 적용
  uniro_frontend/.gitignore
  uniro_frontend/.prettierrc
  uniro_frontend/README.md
  uniro_frontend/eslint.config.js
  uniro_frontend/index.html
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/public/fonts/AppleSDGothicNeoB/AppleSDGothicNeoB.woff
  uniro_frontend/public/fonts/SF_Pro_Display/SF-Pro-Display-Regular.woff
  uniro_frontend/public/vite.svg
  uniro_frontend/src/App.css
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/react.svg
  uniro_frontend/src/index.css
  uniro_frontend/src/main.tsx
  uniro_frontend/src/vite-env.d.ts
  uniro_frontend/tsconfig.app.json
  uniro_frontend/tsconfig.json
  uniro_frontend/tsconfig.node.json
  uniro_frontend/vite.config.ts
Labels: 🚀 feat

#1 [UNI-7] feat: 프로젝트 초기세팅 및 엔티티 정의
  .github/pull_request_template.md
  .gitignore
  uniro_backend/.gitignore
  uniro_backend/build.gradle
  uniro_backend/gradle/wrapper/gradle-wrapper.jar
  uniro_backend/gradle/wrapper/gradle-wrapper.properties
  uniro_backend/gradlew
  uniro_backend/gradlew.bat
  uniro_backend/settings.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/UniroBackendApplication.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/RiskListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/Node.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/CoreRoute.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/RiskType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/Univ.java
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/test/java/com/softeer5/uniro_backend/UniroBackendApplicationTests.java
Labels: ⚙️ chore

#3 [UNI-38] feat: 초기 지도 컴포넌트 및 훅 생성
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/src/App.tsx
  uniro_frontend/src/component/Map.tsx
  uniro_frontend/src/constant/bounds.ts
  uniro_frontend/src/constant/university.ts
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/map/loader/googleMapLoader.ts
Labels: 🚀 feat

#4 [UNI-34] feat: [FE] CI / CD 설정하기
  .github/workflows/fe-deploy.yml
  uniro_frontend/Dockerfile
  uniro_frontend/nginx/nginx.conf
  uniro_frontend/src/component/Map.tsx
  uniro_frontend/src/hooks/useMap.tsx
Labels: ⚙️ chore

#5 [UNI-42] feat : 공통 컴포넌트 제작 (UNI-43, UNI-44, UNI-54)
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoSB.woff
  uniro_frontend/public/icons/chevron-left.svg
  uniro_frontend/public/icons/chevron-right.svg
  uniro_frontend/public/icons/close-circle.svg
  uniro_frontend/public/icons/mic.svg
  uniro_frontend/public/icons/search.svg
  uniro_frontend/src/App.tsx
  uniro_frontend/src/components/customButton.tsx
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/components/landingButton.tsx
  uniro_frontend/src/hooks/useModal.tsx
  uniro_frontend/src/index.css
  uniro_frontend/src/vite-env.d.ts
  uniro_frontend/vite.config.ts
Labels: 🚀 feat

#7 [UNI-14] feat : 길찾기 및 상세경로 안내 로직 작성
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/NodeRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/FastestRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteDetailDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteInfoDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/DirectionType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🚀 feat, 🫀 be

#8 [UNI-64] 건물 노드 조회 API ([UNI-9] last PR)
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/BuildingNode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/main/resources/data.sql
Labels: 🚀 feat, 🫀 be

#10 [UNI-46] [FE] Mock Data 생성하기 (UNI-47, UNI-48)
  uniro_frontend/package.json
  uniro_frontend/src/data/converter/Converter.ts
  uniro_frontend/src/data/factory/edgeFactory.ts
  uniro_frontend/src/data/factory/navigationFactory.ts
  uniro_frontend/src/data/factory/nodeFactory.ts
  uniro_frontend/src/data/mock/hanyangBuildings.ts
  uniro_frontend/src/data/mock/hanyangHazardEdge.ts
  uniro_frontend/src/data/mock/hanyangPath.json
  uniro_frontend/src/data/mock/hanyangRoute.ts
  uniro_frontend/src/data/types/edge.d.ts
  uniro_frontend/src/data/types/factor.d.ts
  uniro_frontend/src/data/types/node.d.ts
  uniro_frontend/src/data/types/path.d.ts
  uniro_frontend/src/data/types/route.d.ts
Labels: 🚀 feat, :waffle: fe

#9 [UNI-62] chore : custom exception handler 정의
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorResponse.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/CustomException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/SameStartAndEndPointException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/UnreachableDestinationException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: ⚙️ chore, 🫀 be

#11 [UNI-12] 건물 노드 검색 API
  uniro_backend/build.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/CursorPage.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/QueryDSLConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/BuildingNode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/SearchBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingCustomRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/CautionListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/DangerListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
Labels: 🚀 feat, 🫀 be

#13 [UNI-6] feat : 랜딩, 학교 검색 페이지 구현 및 라우터 연결 (UNI-40, UNI-45)
  uniro_frontend/package-lock.json
  uniro_frontend/public/background.png
  uniro_frontend/src/App.css
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/UNIRO.svg
  uniro_frontend/src/assets/logo.svg
  uniro_frontend/src/assets/고려대학교.svg
  uniro_frontend/src/assets/서울시립대학교.svg
  uniro_frontend/src/assets/이화여자대학교.svg
  uniro_frontend/src/assets/인하대학교.svg
  uniro_frontend/src/assets/한양대학교.svg
  uniro_frontend/src/components/customButton.tsx
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/components/landingButton.tsx
  uniro_frontend/src/components/universityButton.tsx
  uniro_frontend/src/constant/university.ts
  uniro_frontend/src/index.css
  uniro_frontend/src/main.tsx
  uniro_frontend/src/pages/demo.tsx
  uniro_frontend/src/pages/landing.tsx
  uniro_frontend/src/pages/search.tsx
Labels: 🚀 feat, :waffle: fe

#14 [UNI-67] feat : Vite SVG Dynamic Import 방식 수정
  uniro_frontend/src/assets/university/고려대학교.svg
  uniro_frontend/src/assets/university/서울시립대학교.svg
  uniro_frontend/src/assets/university/이화여자대학교.svg
  uniro_frontend/src/assets/university/인하대학교.svg
  uniro_frontend/src/assets/university/한양대학교.svg
  uniro_frontend/src/components/universityButton.tsx
Labels: 🚀 feat, :waffle: fe

#12 [UNI-63] chore : DTO 생성자를 builder 패턴에서 factory method 패턴으로 통일
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/FastestRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetCautionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetDangerResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetRiskRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteDetailDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteInfoDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: ⚙️ chore, 🫀 be

#15 [UNI-8] 전체 대학교 목록 조회(검색) API 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivAPI.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/SearchUnivResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/UnivInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
Labels: 🚀 feat, 🫀 be

#16 [UNI-11] feat : 대학교 내 모든 루트와 노드를 조회하는 API 개발
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CoreRoute.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/CoreRouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🚀 feat, 🫀 be

#21 [UNI-18] feat : route의 위험요소,주의요소 조회 및 업데이트(수정,삭제,생성) API 개발
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/DangerCautionConflictException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/RouteNotFoundException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/Utils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetRiskResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/PostRiskReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🚀 feat, 🫀 be

#20 [UNI-49] feat : 지도 페이지 구현 (지도 메인, 장소 상세, 건물 검색, 경로 검색) (UNI-50, UNI-55)
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/public/icons/call-thick.svg
  uniro_frontend/public/icons/location-thick.svg
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/call-thin.svg
  uniro_frontend/src/assets/caution.svg
  uniro_frontend/src/assets/danger.svg
  uniro_frontend/src/assets/location-thin.svg
  uniro_frontend/src/assets/map/destination.svg
  uniro_frontend/src/assets/map/origin.svg
  uniro_frontend/src/assets/report.svg
  uniro_frontend/src/assets/switch.svg
  uniro_frontend/src/components/building/buildingCard.tsx
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/floatingButtons.tsx
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/components/map/mapMarkers.tsx
  uniro_frontend/src/components/map/reportButton.tsx
  uniro_frontend/src/components/map/routeSearchInput.tsx
  uniro_frontend/src/data/mock/hanyangHazardEdge.ts
  uniro_frontend/src/data/mock/hanyangPath.json
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/hooks/useRoutePoint.ts
  uniro_frontend/src/hooks/useSearchBuilding.ts
  uniro_frontend/src/index.css
  uniro_frontend/src/main.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/demo.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/search.tsx
Labels: 🚀 feat, :waffle: fe

#22 chore: 릴리즈 노트 추가
  .github/release-drafter-config.yml
Labels: ⚙️ chore
