Repository softeer5th/Team2-Getit, pull requests merged in 2025-02, with the labels that each got.

#25 [UNI-73] refactor : 길찾기 로직 응답형태 리팩토링
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteDetailDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteInfoDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 💡 refactor, 🫀 be

#28 [UNI-86] feat : 길 추가 로직 - 4단계 (노드의 z좌표를 Google Map API를 호출하여 가져오기)
  uniro_backend/build.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/ElevationApiException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/client/MapClient.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/client/MapClientImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/test/java/com/softeer5/uniro_backend/node/client/MapClientImplTest.java
  uniro_backend/src/test/resources/application-test.yml
Labels: 🚀 feat, 🫀 be

#31 [UNI-84] feat: 마커 등장 애니메이션 구현
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/map/mapMarkers.tsx
  uniro_frontend/src/index.css
Labels: 🚀 feat, 🧇 fe

#32 [UNI-81] feat : 새로운 길 제보 페이지 생성 및 길 생성 로직 구현
  uniro_frontend/src/App.tsx
  uniro_frontend/src/constant/edge.ts
  uniro_frontend/src/data/mock/hanyangRoute.ts
  uniro_frontend/src/data/types/event.d.ts
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/pages/universitySearch.tsx
  uniro_frontend/src/utils/coordinates/centerCoordinate.ts
  uniro_frontend/src/utils/coordinates/coordinateTransform.ts
  uniro_frontend/src/utils/coordinates/distance.ts
  uniro_frontend/src/utils/markers/createAdvanedMarker.ts
  uniro_frontend/src/utils/markers/toggleMarkers.ts
  uniro_frontend/src/utils/polylines/createSubnodes.ts
  uniro_frontend/src/utils/polylines/findNearestEdge.ts
Labels: 🚀 feat, 🧇 fe

#33 [UNI-96] fix : RoutePoint Enum 중복 선언 제거
  uniro_frontend/src/constant/enum/markerEnum.ts
  uniro_frontend/src/data/types/route.d.ts
Labels: 🔧 fix, 🧇 fe

#34 [UNI-97] fix : Loading 컴포넌트 빌드 환경 사진 로딩 문제 해결
  uniro_frontend/src/components/loading/loading.tsx
Labels: 🔧 fix, 🧇 fe

#35 [UNI-19] feat : 불편한 길 제보 페이지 생성 및 제보 로직 구현
  .github/workflows/fe-deploy.yml
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/markers/report.svg
  uniro_frontend/src/constant/enum/markerEnum.ts
  uniro_frontend/src/constant/enum/messageEnum.ts
  uniro_frontend/src/data/types/marker.d.ts
  uniro_frontend/src/hooks/useReportHazard.ts
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportHazard.tsx
Labels: 🚀 feat, 🧇 fe

#37 [UNI-30] 어드민 페이지 개발
  .DS_Store
  .github/.DS_Store
  .github/workflows/fe-admin-deploy.yml
  uniro_admin_frontend/.gitignore
  uniro_admin_frontend/Dockerfile
  uniro_admin_frontend/README.md
  uniro_admin_frontend/eslint.config.js
  uniro_admin_frontend/index.html
  uniro_admin_frontend/nginx/nginx.conf
  uniro_admin_frontend/package-lock.json
  uniro_admin_frontend/package.json
  uniro_admin_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.woff
  uniro_admin_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.woff
  uniro_admin_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.woff
  uniro_admin_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoSB.woff
  uniro_admin_frontend/public/fonts/SF_Pro_Display/SF-Pro-Display-Regular.woff
  uniro_admin_frontend/public/vite.svg
  uniro_admin_frontend/src/App.css
  uniro_admin_frontend/src/App.tsx
  uniro_admin_frontend/src/assets/navbar/UNIRO_ADMIN.svg
  uniro_admin_frontend/src/assets/navbar/dropDownArrow.svg
  uniro_admin_frontend/src/assets/react.svg
  uniro_admin_frontend/src/component/Map.tsx
  uniro_admin_frontend/src/components/log/logCard.tsx
  uniro_admin_frontend/src/components/log/logList.tsx
  uniro_admin_frontend/src/components/log/logTitle.tsx
  uniro_admin_frontend/src/components/navBar.tsx
  uniro_admin_frontend/src/constant/university.ts
  uniro_admin_frontend/src/container/logListContainer.tsx
  uniro_admin_frontend/src/container/mainContainer.tsx
  uniro_admin_frontend/src/container/mapContainer.tsx
  uniro_admin_frontend/src/data/mock/logMockData.ts
  uniro_admin_frontend/src/data/types/university.ts
  uniro_admin_frontend/src/hooks/useMap.tsx
  uniro_admin_frontend/src/hooks/useUniversityRecord.tsx
  uniro_admin_frontend/src/index.css
  uniro_admin_frontend/src/main.tsx
  uniro_admin_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_admin_frontend/src/map/loader/googleMapLoader.ts
  uniro_admin_frontend/src/vite-env.d.ts
  uniro_admin_frontend/tsconfig.app.json
  uniro_admin_frontend/tsconfig.json
  uniro_admin_frontend/tsconfig.node.json
  uniro_admin_frontend/vite.config.ts
Labels: 🚀 feat, 🧇 fe

#38 [UNI-98] feat : Tanstack Query 도입 및 커스텀 Fetch 모듈 생성
  uniro_frontend/eslint.config.js
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/src/App.tsx
  uniro_frontend/src/pages/demo.tsx
  uniro_frontend/src/utils/fetch/fetch.ts
Labels: 🚀 feat, 🧇 fe

#36 [UNI-100] refactor : 코어 루트 삭제에 따른 조회 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/InvalidMapException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CoreRouteDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/NodeInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteCoordinatesInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🚀 feat, 💡 refactor, 🫀 be

#41 [UNI-95] feat : 공통 에러 컴포넌트(SearchNull, Error, Offline) 컴포넌트 생성
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/error/error.svg
  uniro_frontend/src/assets/error/offline.svg
  uniro_frontend/src/assets/error/search-null.svg
  uniro_frontend/src/components/error/Error.tsx
  uniro_frontend/src/components/error/Offline.tsx
  uniro_frontend/src/components/error/SearchNull.tsx
  uniro_frontend/src/pages/demo.tsx
Labels: 🚀 feat, 🧇 fe

#40 [UNI-104] chore : document title 변경 및 Favicon 추가
  uniro_admin_frontend/index.html
  uniro_admin_frontend/public/logo.svg
  uniro_admin_frontend/public/vite.svg
  uniro_frontend/index.html
  uniro_frontend/public/vite.svg
Labels: ⚙️ chore, 🧇 fe

#39 [UNI-22] feat: 길 추가 로직 1,2,3 단계 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/NodeNotFoundException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/custom/RouteCalculationException.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteServiceReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/NodeFixture.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/RouteFixture.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🚀 feat, 🫀 be

#42 [UNI-105] feat : 예외 처리 로직 구현
  uniro_frontend/src/App.tsx
  uniro_frontend/src/hooks/useNetworkStatus.tsx
  uniro_frontend/src/hooks/useRedirectUndefined.tsx
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/error.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/offline.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportHazard.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#43 [UNI-108] feat : 페이지간 라우터 연결 및 뒤로가기 공통 컴포넌트 생성
  uniro_frontend/src/components/map/backButton.tsx
  uniro_frontend/src/components/map/reportButton.tsx
  uniro_frontend/src/components/map/reportModal.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/reportHazard.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#44 [UNI-99] feat : Suspense 적용하기
  uniro_admin_frontend/src/fetch/fetch.tsx
  uniro_frontend/src/App.tsx
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/constant/fallback.tsx
  uniro_frontend/src/container/dynamicSuspense.tsx
  uniro_frontend/src/hooks/useDynamicSuspense.tsx
  uniro_frontend/src/hooks/useFallbackStore.tsx
  uniro_frontend/src/hooks/useSuspenseMap.tsx
  uniro_frontend/src/map/createMapResource.ts
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/pages/demo.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/utils/fetch/mockFetch.ts
Labels: 🚀 feat, 🧇 fe

#46 [UNI-116] fix : 전역 Suspense 페이지 전환 시 fallback 없이 freeze 되는 현상 해결
  uniro_frontend/src/App.tsx
  uniro_frontend/src/container/dynamicSuspense.tsx
  uniro_frontend/src/hooks/useDynamicSuspense.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🔧 fix, 🧇 fe

#48 [UNI-111] fix, feat, refactor : QA 문제 해결 (지도 페이지 뷰포트, 마커 동적 스타일 변경, 지도 줌 레벨 감지, 제보하기 모달 PC 환경 스타일)
  uniro_frontend/src/assets/markers/university.svg
  uniro_frontend/src/components/map/reportModal.tsx
  uniro_frontend/src/data/types/node.d.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/utils/markers/createAdvanedMarker.ts
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#51 [UNI-119] 길찾기 결과 바텀 시트 아래로 내릴 시 스크롤 끝까지 안되는 현상
  uniro_frontend/src/container/animatedSheetContainer.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🔧 fix, 🧇 fe

#52 [UNI-120] feat : Tanstack-Query DevTools 라이브러리 설치 및 적용
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/src/App.tsx
Labels: 🚀 feat, 🧇 fe

#53 [UNI-118] chore : CORS 설정 추가
  uniro_backend/.gitignore
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/CorsConfig.java
  uniro_backend/src/main/resources/application-dev.yml
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/main/resources/application-test.yml
Labels: ⚙️ chore, 🫀 be

#54 [UNI-121] chore : 서비스 라우터 변경
  .github/workflows/fe-admin-deploy.yml
  uniro_frontend/src/App.tsx
  uniro_frontend/src/hooks/useRedirectUndefined.tsx
Labels: ⚙️ chore, 🧇 fe

#55 [UNI-122] chore: ddl-auto 수정
  uniro_backend/src/main/resources/application-dev.yml
Labels: ⚙️ chore, 🫀 be

#56 [UNI-126] chore: 스웨거 cors 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/SwaggerConfig.java
  uniro_backend/src/main/resources/application-local.yml
Labels: ⚙️ chore, 🫀 be

#57 [UNI-128] API 공통 타입 선언 및 fetch 디렉토리 정리
  uniro_frontend/src/App.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/data/factory/edgeFactory.ts
  uniro_frontend/src/data/factory/navigationFactory.ts
  uniro_frontend/src/data/mock/hanyangHazardEdge.ts
  uniro_frontend/src/data/mock/hanyangRoute.ts
  uniro_frontend/src/data/types/coord.d.ts
  uniro_frontend/src/data/types/edge.d.ts
  uniro_frontend/src/data/types/node.d.ts
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/pages/reportHazard.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#47 [UNI-87] 길추가 로직 4,5단계 구현 (리팩토링 예정)
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClient.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClientImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteCoordinates.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/node/client/MapClientImplTest.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🚀 feat, 🫀 be

#58 [UNI-131] fix: FE 요청에 따른 수정
  uniro_backend/deploy.sh
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/RevInfoDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/GetBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CoreRouteDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteCoordinates.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/CreateRouteReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/NodeInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/PostRiskReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/RouteCoordinatesInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateRouteReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateRoutesReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/PostRiskReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/CoreRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/FastestRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetCautionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetDangerResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetRiskResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetRiskRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/NodeInfoResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteCoordinatesInfoResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteDetailResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteInfoResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CautionType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/DangerType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/SearchUnivResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/UnivInfo.java
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🔧 fix, 🫀 be

#59 [UNI-132] fix : building node 조회 로직 SQL 오류 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
Labels: 🔧 fix, 🫀 be

#62 [UNI-136] fix: 위도, 경도 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
Labels: 🔧 fix, 🫀 be

#63 [UNI-137] fix : 모든 길 조회 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🔧 fix, 🫀 be

#61 [UNI-66] feat: 로깅 aop 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
Labels: 🚀 feat, 🫀 be

#60 [UNI-134] fix : 분기문 오류로 인한 잘못된 응답 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/CautionListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/resolver/DangerListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetCautionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetDangerResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🔧 fix, 🫀 be

#66 [UNI-134] fix : sql문 오류 해결 - 대소문자
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
Labels: 🔧 fix, 🫀 be

#67 [UNI-141] feat : 길 조회 API 연결
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/pages/reportHazard.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#68 [UNI-143] fix : 스크린 사이즈 dvh로 통일하기
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/error.tsx
  uniro_frontend/src/pages/landing.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/offline.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🔧 fix, 🧇 fe

#69 [UNI-135] fix: 길 추가 API 오류 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevisionOperationType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#70 [UNI-142] feat : 전체 경로 생성 로직 변경, 새로운 길 제보하기 API 연결, 불편한 길 제보하기 GlobalState 재정의
  uniro_frontend/src/App.tsx
  uniro_frontend/src/api/route.ts
  uniro_frontend/src/constant/enum/messageEnum.ts
  uniro_frontend/src/hooks/useReportHazard.ts
  uniro_frontend/src/hooks/useReportRisk.ts
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportHazard.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/utils/coordinates/centerCoordinate.ts
  uniro_frontend/src/utils/markers/createAdvanedMarker.ts
  uniro_frontend/src/utils/polylines/createSubnodes.ts
  uniro_frontend/src/utils/polylines/findNearestEdge.ts
Labels: 🚀 feat, 🧇 fe

#72 [UNI-149] fix : 중복 포인트 삽입 문제 해결 (1, 2, 3, 4, 5, 5, 6, 7, 8) 문제
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🔧 fix, 🧇 fe

#77 [UNI-150] fix : 길찾기 캐시 저장 해제
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🔧 fix, 🧇 fe

#78 [UNI-160] feat & refactor : 길찾기 로직에서 FE 요구사항 반영 및 건물노드 관련 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteDetailResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteInfoResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🚀 feat, 💡 refactor, ⚙️ chore, 🫀 be

#79 [UNI-138] 테스트 환경 복구 및 ci/cd 테스트 환경 구축
  .github/workflows/be-ci.yml
  uniro_backend/build.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Node.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CoreRoute.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/resources/application-test.yml
  uniro_backend/src/test/java/com/softeer5/uniro_backend/UniroBackendApplicationTests.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/RouteFixture.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🔧 fix, 🫀 be

#81 [UNI-172] 코드 리팩토링 (2차)
  uniro_backend/.gitignore
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/resolver/CautionListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/resolver/DangerListConverter.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/PostRiskReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetCautionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetDangerResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetRiskResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteDetailResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/RouteInfoResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/CautionFactor.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/DangerFactor.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
  uniro_backend/src/main/resources/data.sql
Labels: 💡 refactor, 🫀 be

#82 [UNI-174] fix: 빠른 길 계산에서 불변 리스트 반환에 대한 오류 처리
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#85 [UNI-159] fix : 길찾기 결과가 정렬되지 않던 문제 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#84 [UNI-168] feat : 백엔드 API 변경사항 적용 및 코드 리팩토링
  uniro_frontend/src/api/transformer/route.ts
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/hooks/useNavigationBottomSheet.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/utils/navigation/formatDistance.ts
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#87 [UNI-175] feat : Router로 페이지별 작업 환경 설정하기
  uniro_admin_frontend/src/App.tsx
  uniro_admin_frontend/src/AppRouter.tsx
  uniro_admin_frontend/src/components/navBar.tsx
  uniro_admin_frontend/src/components/subNavBar.tsx
  uniro_admin_frontend/src/main.tsx
  uniro_admin_frontend/src/page/buildingPage.tsx
  uniro_admin_frontend/src/page/logPage.tsx
  uniro_admin_frontend/src/page/simulationPage.tsx
Labels: 🚀 feat, 🧇 fe

#88 [UNI-145] feat : 에러 바운더리 생성 및 POST 에러 핸들링 로직
  uniro_frontend/src/App.tsx
  uniro_frontend/src/components/error/ErrorBoundary.tsx
  uniro_frontend/src/constant/error.ts
  uniro_frontend/src/hooks/useMutationError.tsx
  uniro_frontend/src/pages/errorTest.tsx
  uniro_frontend/src/utils/fetch/fetch.ts
Labels: 🚀 feat, 🧇 fe

#89 [UNI-176] fix : API 변수명 변경 적용 (cautionTypes -> cautionFactors, danger…
  uniro_frontend/src/api/route.ts
  uniro_frontend/src/api/type/response/route.d.ts
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🔧 fix, 🧇 fe

#90 [UNI-177] feat : ADMIN 페이지, 선택 간선, 노드 ID 조회 페이지 생성
  uniro_admin_frontend/package-lock.json
  uniro_admin_frontend/package.json
  uniro_admin_frontend/src/AppRouter.tsx
  uniro_admin_frontend/src/assets/markers/building.svg
  uniro_admin_frontend/src/assets/markers/caution.svg
  uniro_admin_frontend/src/assets/markers/danger.svg
  uniro_admin_frontend/src/assets/markers/destination.svg
  uniro_admin_frontend/src/assets/markers/origin.svg
  uniro_admin_frontend/src/assets/markers/report.svg
  uniro_admin_frontend/src/assets/markers/selectedBuilding.svg
  uniro_admin_frontend/src/assets/markers/university.svg
  uniro_admin_frontend/src/assets/markers/waypoint.svg
  uniro_admin_frontend/src/assets/markers/waypoint_blue.svg
  uniro_admin_frontend/src/assets/markers/waypoint_red.svg
  uniro_admin_frontend/src/components/map/mapMarkers.tsx
  uniro_admin_frontend/src/data/types/coord.d.ts
  uniro_admin_frontend/src/data/types/node.d.ts
  uniro_admin_frontend/src/data/types/route.d.ts
  uniro_admin_frontend/src/page/simulationPage.tsx
  uniro_admin_frontend/src/utils/coordinates/centerCoordinate.ts
  uniro_admin_frontend/src/utils/coordinates/coordinateTransform.ts
  uniro_admin_frontend/src/utils/coordinates/distance.ts
  uniro_admin_frontend/src/utils/polylines/createSubnodes.ts
  uniro_admin_frontend/src/utils/polylines/findNearestEdge.ts
  uniro_admin_frontend/src/utils/route.ts
Labels: 🚀 feat, 🧇 fe

#92 [UNI-145] fix : 에러 테스트 페이지 백엔드 API 요청, 필드명 변경
  uniro_frontend/src/pages/errorTest.tsx
Labels: 🔧 fix, 🧇 fe

#83 [UNI-154, UNI-155] feat : 빌딩 노드 추가 API 개발
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevisionOperationType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/GeoUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/request/CreateBuildingNodeReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/response/GetBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/response/SearchBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/entity/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/service/NodeService.java
Labels: 🚀 feat, 🫀 be

#94 [UIN-184] 길찾기 로직에서 좌/우회전이 반대로 적용되던 오류 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/CoreRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#93 [UNI-178], [UNI-179] fix : 클라이언트 요청값 검증 로직 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateRoutesReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/PostRiskReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#95 [UNI-185] fix: 기존 선과 동일하거나 겹치는 경우 예외 발생 (일반 크로스 체크와 self 크로스에 따라 분기처리)
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🔧 fix, 🫀 be

#97 [UNI-180] 건물 추가 API 연결 및 건물 -> 길 이어주는 UI 및 state 생성
  uniro_admin_frontend/src/api/nodes.ts
  uniro_admin_frontend/src/container/building/buildingAddContainer.tsx
  uniro_admin_frontend/src/container/building/buildingMapContainer.tsx
  uniro_admin_frontend/src/page/buildingPage.tsx
Labels: 🚀 feat, 🧇 fe

#98 [UNI-167] feat, fix, refactor : 구글 구면좌표계 도입, QA waypoint 마커 제거, 새로운 길 제보시 되돌리기 기능 구현
  uniro_frontend/src/assets/undo.svg
  uniro_frontend/src/components/map/floatingButtons.tsx
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/map/loader/googleMapLoader.ts
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/utils/coordinates/centerCoordinate.ts
  uniro_frontend/src/utils/coordinates/distance.ts
  uniro_frontend/src/utils/markers/removeMarkers.ts
  uniro_frontend/src/utils/markers/toggleMarkers.ts
  uniro_frontend/src/utils/polylines/createSubnodes.ts
  uniro_frontend/src/utils/polylines/findNearestEdge.ts
Labels: 🚀 feat, 🔧 fix, 💡 refactor, 🧇 fe

#99 [UNI-158] fix : 빌딩노드와 연결된 간선은 조회되지 않도록 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/RouteUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🔧 fix, 🫀 be

#96 [UNI-156] 빌딩과 연결된 간선 API 개발
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/RevisionOperationType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/utils/RouteUtils.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/controller/NodeController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/dto/request/CreateBuildingNodeReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/node/repository/BuildingRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/controller/RouteController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/request/CreateBuildingRouteReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🚀 feat, 🫀 be

#101 [UNI-189] feat : 건물 -> 길 연결 API 반영
  uniro_admin_frontend/src/api/route.ts
  uniro_admin_frontend/src/container/building/buildingAddContainer.tsx
Labels: 🚀 feat, 🧇 fe

#100 [UNI-187] fix : Param으로 받지 않고, Building으로 검색했을 때 위치가 변동되지 않는 문제 해결
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 🧇 fe

#102 [UNI-188] refactor : 불편한 길 제보 페이지 & 새로운 길 제보 페이지 useMutation -> useMutationError 변경
  uniro_frontend/src/hooks/useMutationError.tsx
  uniro_frontend/src/pages/errorTest.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 💡 refactor, 🧇 fe

#104 [UNI-191] fix : 변수 하드코딩 제거
  uniro_frontend/src/api/route.ts
Labels: 🔧 fix, 🧇 fe

#105 [UNI-192] QA : 길찾기 로직 예외처리 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
Labels: 🔧 fix, 🫀 be

#106 [UNI-193] 모든 길 조회 로직에서 building route를 따로 제공하는 로직 추가
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/BuildingRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/dto/response/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteService.java
Labels: 🚀 feat, 🔧 fix, 🫀 be

#108 [UNI-200] google map API 최대 batch size 조정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/MapClientImpl.java
Labels: 🔧 fix, 🫀 be

#107 [UNI-133] fix: 길 추가에서 셀프 크로스 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/route/service/RouteCalculationService.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/route/RouteCalculationServiceTest.java
Labels: 🔧 fix, 💡 refactor, 🫀 be

#114 [UNI-207] fix : 일부 모바일 브라우저에서 form이 x축으로 스크롤이 가능한 문제
  uniro_frontend/src/pages/reportForm.tsx
Labels: 🔧 fix, 🧇 fe

#113 [UNI-206] fix : 건물 마커 클릭시 지도가 건물 정 가운데로 오지 않는 문제 해결
  uniro_frontend/src/pages/map.tsx
Labels: 🔧 fix, 🧇 fe

#110 [UNI-195] Post 요청에 대한 debounce 적용
  uniro_frontend/src/hooks/useDebounceMutation.tsx
  uniro_frontend/src/hooks/useMutationError.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#116 [UNI-212] feat : 위험 주의 마커 요소 여러개인 경우 애니메이션 추가
  uniro_frontend/src/components/map/mapMarkers.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRisk.tsx
Labels: 🚀 feat, 🧇 fe

#115 [UNI-201] fix : (QA 수정 사항) 지도 메인페이지 줌 아웃시 위험 주의 비활성화 로직 제거 / 불편한 길 반영 시, 캐시 초기화 적용 / 지도 제스쳐 핸들링 방식 변경
  uniro_frontend/src/hooks/useMutationError.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/utils/fetch/fetch.ts
Labels: 🔧 fix, 🧇 fe

#117 [UNI-211] feat : 건물과 길을 이어주는 길 생성
  uniro_frontend/src/component/NavgationMap.tsx
Labels: 🚀 feat, 🧇 fe

#118 [UNI-215] fix : 구글 구면좌표계 제거 및 interpolate 함수 및 distance 함수 구현
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/map/loader/googleMapLoader.ts
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/utils/coordinates/centerCoordinate.ts
  uniro_frontend/src/utils/coordinates/distance.ts
  uniro_frontend/src/utils/interpolate.ts
  uniro_frontend/src/utils/polylines/createSubnodes.ts
  uniro_frontend/src/utils/polylines/findNearestEdge.ts
Labels: 🔧 fix, 🧇 fe

#120 [UNI-208] refactor : 지도 메인 페이지 바텀 시트 react-spring-bottom-sheet 라이브러리 제거
  uniro_frontend/package-lock.json
  uniro_frontend/package.json
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/pages/map.tsx
Labels: 💡 refactor, 🧇 fe

#124 [UNI-24] 특정 revision의 맵 정보 조회 API 개발
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AdminApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AdminController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/ChangedRouteDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/GetAllRoutesByRevisionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/LostRoutesDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/RevInfoDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/RouteDifferInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/RouteDetailResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/RouteFixture.java
Labels: 🚀 feat, 🫀 be

#125 [UNI-139] refactor: 로깅 메세지 가독성 좋게 변경
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ArgType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
Labels: 💡 refactor, 🫀 be

#126 [UNI-216] fix : 길 찾기 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 🔧 fix, 🫀 be

#129 [UNI-230] hotfix : 불편한 길 제보하기 코드 오타 수정
  uniro_frontend/src/pages/reportForm.tsx
Labels: 🔧 fix, 🧇 fe

#128 [UNI-219] feat: 로그인 기능 구현 및 JWT 인터셉터 구현
  uniro_backend/build.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AuthApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/controller/AuthController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/request/LoginReqDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/LoginResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/entity/Admin.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/interceptor/AdminInterceptor.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/interceptor/JwtInterceptor.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/jwt/JwtTokenProvider.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/jwt/SecurityContext.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/AdminRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AuthService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/WebMvcConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/resources/application-dev.yml
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/main/resources/application-test.yml
Labels: 🚀 feat, 🫀 be

#127 [UNI-221] feat : 지도 메인페이지 UX 개선 및 길찾기 사용자 로직 변경
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/components/map/mapSearchInput.tsx
  uniro_frontend/src/hooks/useSearchBuilding.ts
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/demo.tsx
  uniro_frontend/src/pages/map.tsx
Labels: 🚀 feat, 🧇 fe

#136 [UNI-77] feat : 한글 debounced 입력 구현 / 학교 검색, 건물 검색 API 연결
  uniro_frontend/src/api/nodes.ts
  uniro_frontend/src/api/search.ts
  uniro_frontend/src/api/transformer/nodes.ts
  uniro_frontend/src/api/type/response/nodes.d.ts
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#133 [UNI-217] fix: 길 추가시 동일한 노드 판단 로직 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/MapServiceTest.java
Labels: 🔧 fix, 🫀 be

#135 [UNI-213] feat: 롤백 기능시 건물노드 삭제 기능 포함
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/entity/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingRepository.java
Labels: 🚀 feat, 🫀 be

#138 [UNI-239] 지도 메인페이지 UI 2차 개선
  uniro_frontend/src/App.tsx
  uniro_frontend/src/assets/markers/building.svg
  uniro_frontend/src/assets/markers/selectedBuilding.svg
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/map/floatingButtons.tsx
  uniro_frontend/src/components/map/mapMarkers.tsx
  uniro_frontend/src/components/map/reportButton.tsx
  uniro_frontend/src/index.css
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRisk.tsx
Labels: 🚀 feat, 🧇 fe

#134 [UNI-222] feat : 길찾기 변경된 UX로 개선 및 추가 기능 도입(여러 길을 한번에 조회)
  .github/workflows/fe-deploy.yml
  uniro_frontend/src/api/route.ts
  uniro_frontend/src/api/transformer/route.ts
  uniro_frontend/src/api/type/response/route.d.ts
  uniro_frontend/src/assets/icon/cautionTextWhite.svg
  uniro_frontend/src/assets/icon/safeTextWhite.svg
  uniro_frontend/src/assets/route/detail/electric.svg
  uniro_frontend/src/assets/route/detail/pedestrian.svg
  uniro_frontend/src/assets/route/detail/wheelchair.svg
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/card/bottomCard.tsx
  uniro_frontend/src/components/navigation/card/bottomCardList.tsx
  uniro_frontend/src/components/navigation/navBar/navigationNavBar.tsx
  uniro_frontend/src/components/navigation/navigationDescription.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/index.css
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/tsconfig.app.json
Labels: 🚀 feat, 🧇 fe

#142 [UNI-237] fix: 대학교 및 건물 이름 순으로 조회하도록 수정 맟 페이지네이션 삭제
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/controller/BuildingApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/controller/BuildingController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/dto/response/SearchBuildingResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/controller/UnivController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/SearchUnivResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
Labels: 🔧 fix, 🫀 be

#144 [UNI-244] feat: 학교마다 좌표 및 폴리곤 반환 기능 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/dto/UnivInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
Labels: 🚀 feat, 🫀 be

#145 [UNI-232] 길 찾기 알고리즘 마이그레이션 (다익스트라 -> A*)
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/NodeFixture.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/RouteCalculatorTest.java
Labels: 🚀 feat, 🫀 be

#146 [UNI-248] fix : 주의 경로와 안전 경로가 동일할 시 안전 경로만 나오도록 수정
  uniro_frontend/src/api/transformer/route.ts
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/card/bottomCardList.tsx
  uniro_frontend/src/components/navigation/navBar/navigationNavBar.tsx
  uniro_frontend/src/components/navigation/navigationDescription.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#143 [UNI-238] feat : 현재 버전과 특정 버전의 차이점 조회 API 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/ChangedRouteDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RouteAuditRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/RevisionContext.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetChangedRoutesByRevisionResDTO.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
  uniro_backend/src/test/resources/sql/delete-all-data.sql
Labels: 🚀 feat, 🫀 be

#148 [UNI-250] feat : 길찾기 바텀시트 번호 클릭시 이동 (hotfix 포함)
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/bottomSheet/bottomSheetHandle.tsx
  uniro_frontend/src/components/navigation/card/bottomCardList.tsx
  uniro_frontend/src/components/navigation/navigationDescription.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/hooks/useNavigationBottomSheet.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#150 [UNI-254] feat : 위험 마커 축소, 위험 마커 Animation 및 마커 설명 삽입
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/map/mapMarkers.tsx
  uniro_frontend/src/utils/markers/createRiskMarker.ts
Labels: 🚀 feat, 🧇 fe

#149 [UNI-249] feat: 현재 버전에 대한 버전 반환 기능 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/dto/response/GetAllRoutesByRevisionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RevInfoRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/AllRoutesInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetChangedRoutesByRevisionResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
Labels: 🚀 feat, 🫀 be

#153 [UNI-224] 배포(www<->admin) 주소 바뀌는 현상 fix
  .github/workflows/fe-admin-deploy.yml
  .github/workflows/fe-deploy.yml
Labels: 🔧 fix, ⚙️ chore, 🧇 fe

#152 [UNI-260] fix : CORS allowedHeaders에 Authorization 명시
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/CorsConfig.java
Labels: 🚀 feat, 🫀 be

#155 [UNI-256] feat : 길찾기 페이지 주의 요소 클릭 시 지도 및 바텀 시트 이동
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 🧇 fe

#151 [UNI-257] feat : 지도 메인 페이지 2차 UX 개선 (줌 레벨 조정에 따른 건물 이름 노출 로직 적용, 출발 도착 선택 시 지도 줌 변경)
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/index.css
  uniro_frontend/src/pages/map.tsx
Labels: 🚀 feat, 🧇 fe

#156 [UNI-264] refactor : aud 테이블에서 조회하던 쿼리문 최적화
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/NodeAuditRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RouteAuditRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/entity/Route.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/NodeRepository.java
Labels: 🔧 fix, 💡 refactor, 🫀 be

#157 [UNI-263] feat : 학교 관련 기능 작업
  uniro_frontend/src/assets/icon/graduationCap.svg
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/mapSearchInput.tsx
  uniro_frontend/src/data/types/university.d.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#158 [UNI-272] feat : origin destination persist로 저장, 길찾기시 로딩 화면 생성(이미지 추가)
  uniro_frontend/src/components/loading/loading.tsx
  uniro_frontend/src/hooks/useRoutePoint.ts
  uniro_frontend/src/hooks/useSearchBuilding.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#160 [UNI-276] hotfix : 대학 bounds 제거
  uniro_frontend/src/pages/map.tsx
Labels: 🔧 fix, 🧇 fe

#161 [UNI-277] hotfix : QueryClient Stale default 값 설정
  uniro_admin_frontend/src/AppRouter.tsx
  uniro_frontend/src/App.tsx
Labels: 🔧 fix, 🧇 fe

#163 [UNI-280] fix: oom 추적을 위한 추가
  uniro_backend/Dockerfile
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/exception/GlobalExceptionHandler.java
Labels: 🔧 fix, 🫀 be

#165 [UNI-284] feat : 길 제보하기, 길 신고하기 초기 좌표 대학에 맞게 변경
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#166 [UNI-285] fix: revinfo 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/aspect/RevisionOperationAspect.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/CustomReversionListener.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/setting/RevisionContext.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
Labels: 🔧 fix, 🫀 be

#168 [UNI-285] fix: 컨테이너 수정
  uniro_backend/Dockerfile
Labels: 🔧 fix, 🫀 be

#167 [UNI-267] refactor : createMarkerElement 재 함수화 및 적용
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/data/types/marker.d.ts
  uniro_frontend/src/index.css
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/utils/markers/createMarkerElement.ts
  uniro_frontend/src/utils/markers/createRiskMarker.ts
Labels: 💡 refactor, 🧇 fe

#170 [UNI-286] fitBounds의 원활한 이동을 위한 map minZoom Level 조정
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
Labels: 🔧 fix, 🧇 fe

#172 [UNI-279] fix : IOS Safari Browser 레이아웃 깨짐 해결
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/pages/buildingSearch.tsx
Labels: 🔧 fix, 🧇 fe

#173 [UNI-289] feat: 프로메테우스 추가
  uniro_backend/build.gradle
Labels: 🚀 feat, 🫀 be

#171 [UNI-287] fix: 롤백 로직 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
Labels: 🔧 fix, 🫀 be

#174 [UNI-294] feat: 음성인식 검색 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/entity/Building.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/repository/BuildingCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/repository/UnivCustomRepositoryImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/service/UnivService.java
Labels: 🚀 feat, 🫀 be

#175 [UNI-290] 각 페이지 별 방어 코드 및 버그 수정
  uniro_frontend/src/components/loading/loading.tsx
  uniro_frontend/src/hooks/useUniversityInfo.tsx
  uniro_frontend/src/pages/landing.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#177 [UNI-300] fix: 롤백 최신 버전 찾는 로직 오류 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/repository/RevInfoRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/main/resources/data.sql
Labels: 🔧 fix, 🫀 be

#178 [UNI-288] feat : github cache를 사용한 빌드 속도 개선
  .github/workflows/fe-admin-deploy.yml
  .github/workflows/fe-deploy.yml
  uniro_admin_frontend/Dockerfile
  uniro_admin_frontend/src/App.tsx
  uniro_frontend/.dockerignore
  uniro_frontend/.gitignore
  uniro_frontend/Dockerfile
  uniro_frontend/src/App.tsx
Labels: ⚙️ chore, 🧇 fe

#179 [UNI-229] feat : 어드민 페이지 버전 롤백 시스템 구현
  uniro_admin_frontend/.prettierrc
  uniro_admin_frontend/eslint.config.js
  uniro_admin_frontend/src/api/admin.ts
  uniro_admin_frontend/src/api/transformer/admin.ts
  uniro_admin_frontend/src/api/type/response/admin.d.ts
  uniro_admin_frontend/src/assets/markers/changed.svg
  uniro_admin_frontend/src/assets/markers/created.svg
  uniro_admin_frontend/src/assets/markers/removed.svg
  uniro_admin_frontend/src/component/LogMap.tsx
  uniro_admin_frontend/src/components/log/failModal.tsx
  uniro_admin_frontend/src/components/log/infoModal.tsx
  uniro_admin_frontend/src/components/log/logCard.tsx
  uniro_admin_frontend/src/components/log/logList.tsx
  uniro_admin_frontend/src/components/log/rollbackModal.tsx
  uniro_admin_frontend/src/constant/enum/markerEnum.ts
  uniro_admin_frontend/src/container/logListContainer.tsx
  uniro_admin_frontend/src/container/mapContainer.tsx
  uniro_admin_frontend/src/data/types/enum.d.ts
  uniro_admin_frontend/src/data/types/revision.d.ts
  uniro_admin_frontend/src/data/types/route.d.ts
  uniro_admin_frontend/src/index.css
  uniro_admin_frontend/src/page/logPage.tsx
  uniro_admin_frontend/src/utils/fetch/fetch.ts
  uniro_admin_frontend/src/utils/markers/createMarkerElement.ts
Labels: 🚀 feat, 🧇 fe

#180 [UNI-305] feat : 랜딩페이지, 학교 검색 관련 기능 추가
  uniro_frontend/src/components/universityButton.tsx
  uniro_frontend/src/pages/landing.tsx
  uniro_frontend/src/pages/universitySearch.tsx
Labels: 🚀 feat, 🧇 fe

#182 [UNI-316] refactor : 빌딩과 연결된 간선은 길 추가 시 크로스체크 하지 않도록 변경
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 💡 refactor, 🫀 be

#183 [UNI-307] feat : 지도 메인 페이지 경로 노출 적용 및 길 색상 변경 및 학교 영역 폴리곤 생성
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/initializer/googleMapInitializer.ts
  uniro_frontend/src/map/loader/googleMapLoader.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🚀 feat, 🧇 fe

#184 [UNI-323] feat : Stream + SSE로 대용량 조회 분할처리 로직 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/UniroBackendApplication.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/AsyncConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
Labels: 🚀 feat, 🫀 be

#185 [UNI-218] refactor : 길 찾기 상세경로 좌회전,우회전 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 💡 refactor, 🫀 be

#188 [UNI-314] refac : Apple Font 제거 및(FOUT 현상 해결) Image 관련 최적화
  uniro_frontend/index.html
  uniro_frontend/public/background.png
  uniro_frontend/public/background.webp
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.woff
  uniro_frontend/public/fonts/AppleSDGothicNeo/AppleSDGothicNeoSB.woff
  uniro_frontend/public/fonts/SF_Pro_Display/SF-Pro-Display-Regular.woff
  uniro_frontend/public/loading/spinner.gif
  uniro_frontend/public/loading/spinner.svg
  uniro_frontend/src/components/loading/loading.tsx
  uniro_frontend/src/index.css
  uniro_frontend/src/pages/landing.tsx
Labels: 🚀 feat, 🧇 fe

#189 [UNI-335] feat : 어드민 페이지 / 로그 변경사항 마커 클릭시 안내 사항 변경 및 빌딩 추가 로직 오류 수정 / 롤백 페이지 새로고침 버튼 추가
  uniro_admin_frontend/src/api/nodes.ts
  uniro_admin_frontend/src/assets/markers/building.svg
  uniro_admin_frontend/src/component/LogMap.tsx
  uniro_admin_frontend/src/components/log/infoModal.tsx
  uniro_admin_frontend/src/components/log/logCard.tsx
  uniro_admin_frontend/src/components/log/logTitle.tsx
  uniro_admin_frontend/src/constant/enum/markerEnum.ts
  uniro_admin_frontend/src/container/building/buildingAddContainer.tsx
  uniro_admin_frontend/src/container/logListContainer.tsx
  uniro_admin_frontend/src/container/mapContainer.tsx
  uniro_admin_frontend/src/index.css
  uniro_admin_frontend/src/page/buildingPage.tsx
  uniro_admin_frontend/src/page/logPage.tsx
  uniro_admin_frontend/src/page/loginPage.tsx
  uniro_admin_frontend/src/utils/fetch/fetch.ts
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#192 [UNI-334] fix : FE Deploy code 수정
  .github/workflows/fe-admin-deploy.yml
  .github/workflows/fe-deploy.yml
Labels: 🔧 fix, ⚙️ chore, 🧇 fe

#191 [UNI-336] 제보하기 페이지 등록 이후 위치 이동 구현, 제보 취소, 제보 후 캐시 수정 구현
  uniro_frontend/src/components/report/reportTitle.tsx
  uniro_frontend/src/hooks/useReportRiskResult.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRisk.tsx
Labels: 🚀 feat, 🔧 fix, 🧇 fe

#194 [UNI-342] fix : 다른 학교로 이동하는 현상 해결
  uniro_frontend/src/pages/reportRisk.tsx
Labels: 🔧 fix, 🧇 fe

#186 [UNI-328] feat : 길 추가 요청 응답값에 생성된 길 정보 제공
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapApi.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/GetAllRoutesResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
Labels: 🚀 feat, 🫀 be

#187 [UNI-330] feat : SSE 요청 시 batchSize를 함께 리턴하도록 구현
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/AllRoutesInfo.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
Labels: 🚀 feat, 🫀 be

#196 [UNI-344] fix : 도보에서는 위험요소도 반영되도록 변경
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/FastestRouteResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/enums/DirectionType.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 🔧 fix, 🫀 be

#190 [UNI-333] 특정 버전 미만으로 롤백 방지 & 6km 이상 길 추가 방지 로직 작성
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/error/ErrorCode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/univ/entity/Univ.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
  uniro_backend/src/test/resources/sql/insert-univ-data.sql
Labels: 🚀 feat, 🫀 be

#198 [UNI-352] refactor : DangerFactor 누락 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/response/RouteDetailResDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 🔧 fix, 🫀 be

#197 [UNI-255] refactor: 캐시를 활용한 응답 시간 개선 & 직렬화 시간 개선
  uniro_backend/Dockerfile
  uniro_backend/build.gradle
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/WebMvcConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/redis/RedisConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/redis/RedisService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/controller/MapController.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCacheCalculator.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/vo/LightNode.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/vo/LightRoute.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/vo/LightRoutes.java
  uniro_backend/src/main/resources/application-dev.yml
  uniro_backend/src/main/resources/application-local.yml
  uniro_backend/src/test/java/com/softeer5/uniro_backend/admin/AdminServiceTest.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/MapServiceTest.java
Labels: 💡 refactor, 🫀 be

#195 [UNI-313] feat : 초기 로딩시 필요없는 화면에 대해 Lazy Loading 적용
  uniro_frontend/src/App.tsx
Labels: 💡 refactor, 🧇 fe

#201 [UNI-255-v4] refactor: 스트림 기반 redis 구현 및 경량객체 조회하도록 개선 (UNI-321)
  uniro_backend/src/main/java/com/softeer5/uniro_backend/admin/service/AdminService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/RedisConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/WebMvcConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClient.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClientImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/redis/RedisService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/vo/LightRoute.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/external/MapClientImplTest.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/MapServiceTest.java
Labels: 💡 refactor, 🫀 be

#202 [UNI-345] refac : 길 찾기 페이지 레이아웃 관련 리팩토링
  uniro_frontend/src/api/transformer/route.ts
  uniro_frontend/src/api/type/response/route.d.ts
  uniro_frontend/src/assets/icon/dangerText.svg
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/mapSearchInput.tsx
  uniro_frontend/src/components/navigation/card/bottomCard.tsx
  uniro_frontend/src/components/navigation/navigationDescription.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/components/navigation/route/routeList.tsx
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 💡 refactor, 🧇 fe

#200 [UNI-304] refactor : 지도 최상위 Provider 생성 / 오브젝트 (Polyline, Marker)캐시화로 인한 메모리 효율 개선 / 캐시 시스템을 위한 렌더링 체계 변경 / 제보 이후 재 제보를 위한 서버 캐시 초기화
  uniro_frontend/src/App.tsx
  uniro_frontend/src/api/route.ts
  uniro_frontend/src/component/Map.tsx
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/hooks/useMap.tsx
  uniro_frontend/src/map/loader/googleMapLoader.ts
  uniro_frontend/src/map/mapCacheContext.tsx
  uniro_frontend/src/map/mapContext.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportForm.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
  uniro_frontend/src/utils/fetch/fetch.ts
  uniro_frontend/src/utils/map/removeAllListener.ts
  uniro_frontend/src/utils/markers/createAdvanedMarker.ts
  uniro_frontend/src/utils/markers/createRiskMarker.ts
Labels: 💡 refactor, 🧇 fe

#204 [FE-356] fix : 길 찾기 페이지 바텀시트 스크롤 x 차단
  uniro_frontend/src/components/navigation/route/routeList.tsx
Labels: 🔧 fix, 🧇 fe

#205 [UNI-357] fix : QA 버그 수정
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🔧 fix, 🧇 fe

#206 [UNI-355] fix : 특정 버전 조회 오류 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCacheCalculator.java
Labels: 🔧 fix, 🫀 be

#208 [UNI-351] fix : 길 찾기 상세에서 체크포인트 갱신이 안되던 상황 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
Labels: 🔧 fix, 🫀 be

#203 [UNI-354] feat : 이벤트를 통한 Google API호출 + 배치로 처리하는 로직 작성
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/config/SchedulerConfig.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/logging/ExecutionLoggingAop.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClientImpl.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteCreatedEvent.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteEventListener.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/event/RouteEventService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/entity/Node.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/enums/HeightStatus.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/NodeRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/fixture/NodeFixture.java
Labels: 🚀 feat, 🫀 be

#210 [UNI-358] 데모데이 버그 수정
  uniro_frontend/src/api/nodes.ts
  uniro_frontend/src/assets/icon/graduationCap.svg
  uniro_frontend/src/components/building/buildingCard.tsx
  uniro_frontend/src/components/building/buildingList.tsx
  uniro_frontend/src/components/customInput.tsx
  uniro_frontend/src/components/loading/innerLoading.tsx
  uniro_frontend/src/components/loading/loading.tsx
  uniro_frontend/src/components/map/TopSheet.tsx
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/components/universityButton.tsx
  uniro_frontend/src/pages/buildingSearch.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🔧 fix, 🧇 fe

#212 [UNI-282] SEO 개선하기
  uniro_frontend/index.html
  uniro_frontend/public/robots.txt
Labels: 🚀 feat, 🧇 fe

#213 [UNI-364] refactor : 길 찾기 로직에서 cost산정방식 변경 & 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/FastestRouteDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/dto/FastestRouteResultDTO.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/RouteCalculator.java
  uniro_backend/src/test/java/com/softeer5/uniro_backend/map/service/RouteCalculatorTest.java
Labels: 💡 refactor, 🫀 be

#214 [UNI-340] refactor : Google API 비동기 처리 최적화 & Google API 호출 최대 개수 조정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/common/constant/UniroConst.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/external/elevation/MapClientImpl.java
Labels: 💡 refactor, 🫀 be

#215 [UNI-363] fix : 길 찾기 버그 수정 및 데모데이 피드백에 따른 UX 개선
  uniro_frontend/src/api/transformer/route.ts
  uniro_frontend/src/assets/route/detail/walkIcon.svg
  uniro_frontend/src/component/NavgationMap.tsx
  uniro_frontend/src/components/navigation/card/bottomCardList.tsx
  uniro_frontend/src/components/navigation/navBar/navigationNavBar.tsx
  uniro_frontend/src/components/navigation/navigationDescription.tsx
  uniro_frontend/src/components/navigation/route/routeCard.tsx
  uniro_frontend/src/data/types/route.d.ts
  uniro_frontend/src/pages/navigationResult.tsx
Labels: 🚀 feat, 🧇 fe

#216 [UNI-365] OG TAG image 추가
  uniro_frontend/index.html
Labels: 🚀 feat, 🧇 fe

#217 [UNI-355] fix: NotNull 문제 해결
  uniro_backend/src/main/java/com/softeer5/uniro_backend/building/service/BuildingService.java
Labels: 🔧 fix, 🫀 be

#209 [UNI-357] refactor, fix : 출발지 도착지 중복 설정 방지 / 출발지 선택 후 새로고침 시 탑 시트 오류 수정
  uniro_frontend/src/components/map/mapBottomSheet.tsx
  uniro_frontend/src/hooks/useRoutePoint.ts
  uniro_frontend/src/pages/map.tsx
  uniro_frontend/src/pages/reportRisk.tsx
  uniro_frontend/src/pages/reportRoute.tsx
Labels: 🔧 fix, 🧇 fe

#219 [UNI-329] stream 사이즈 변경 & 배치사이즈 응답 로직 수정
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/repository/RouteRepository.java
  uniro_backend/src/main/java/com/softeer5/uniro_backend/map/service/MapService.java
Labels: 🔧 fix, 💡 refactor, 🫀 be
